// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAIrAAoaosvUcMsZS18MsV3IYySuWs_Ts',
    appId: '1:997604041112:web:ecb94d28e7f2e888b58bed',
    messagingSenderId: '997604041112',
    projectId: 'bath-mate',
    databaseURL: 'https://bath-mate-default-rtdb.firebaseio.com/',
    authDomain: 'bath-mate.firebaseapp.com',
    storageBucket: 'bath-mate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi4y2UqMKf-6vQX_m_HprdAme6HqUkwCs',
    appId: '1:997604041112:android:b3e18b6839f01f70b58bed',
    messagingSenderId: '997604041112',
    projectId: 'bath-mate',
    databaseURL: 'https://bath-mate-default-rtdb.firebaseio.com/',
    storageBucket: 'bath-mate.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAIrAAoaosvUcMsZS18MsV3IYySuWs_Ts',
    appId: '1:997604041112:web:8de135dee6712dfbb58bed',
    messagingSenderId: '997604041112',
    projectId: 'bath-mate',
    authDomain: 'bath-mate.firebaseapp.com',
    // databaseURL: 'https://bath-mate-default-rtdb.firebaseio.com/',
    storageBucket: 'bath-mate.appspot.com',
  );
}
